### ISSUE TITLE
Consistent UUIDs between staging and production

### ISSUE THREAD

**Issue by danielballan** [edgi-govdata-archiving/web-monitoring-db#152]
The same Version gets different UUIDs in our staging and production deployments because it is up to the app to (randomly) generate those UUIDs.

@Mr0grog raised the possibility of having the client that submits the Versions provide the UUIDs, in which case they would be consistent. I have some reservations about trusting the submitter to generate correct UUIDs. Maybe that paranoia is overly colored by my work experience with scientists who continually try to subvert UUIDs by shoehorning metadata into them. ("Why use UUID4 when you can use `experiment_5_290K_Si_good_one`?")

Alternatively, we could wipe the staging database every night and replace it with a copy of the production one. This has the (future) benefit of also syncing annotations, etc.

**Comment by danielballan** [comment]
[If you are following this via email, I fear that typos rendered my previous comment uninterpretable. See GitHub for an edited version.]

**Comment by Mr0grog** [comment]
> I have some reservations about trusting the submitter to generate correct UUIDs.

Yeah, this is one of the reasons I did not make the existing importer(s) actually send IDs. Though we are in control of existing ones and can make a reasonable assumption of good UUIDs not colliding, I was worried about the possibility still existing and of setting expectations future clients might not meet.

Another option here is to make IDs stable and predictable instead of random UUIDs, e.g. `hash(url + source + capture_time)` for versions. I don’t know that there’s any real natural key for pages, though, since we know the elephant in the room there is that a URL can change (even though we have no strategy for handling that yet).

> Alternatively, we could wipe the staging database every night and replace it with a copy of the production one. This has the (future) benefit of also syncing annotations, etc.

I’d thought about this, but it felt like unnecessary work. I’m also not sure whether we really *want* a future where the staging DB largely matches production: staging is already a giant pain in that I get about 30 e-mails a day about it crumbling under load because it’s runner on cheaper infra than production; I don’t want to have to maintain it like I’d do production; and I’d rather be using it for very brief QA before sending new work off to production hidden behind feature flags.

ALSO, we have different users on staging and production, so annotations aren’t really sync-able. (Side note: do we want to change that?)

**Comment by danielballan** [comment]
Stepping back, maybe syncing isn't as necessary as I first thought. The original motivation here was: I was collecting UUIDs of interesting/challenging cases, and some of them we identified through the staging deployment, such as the problem case we discovered during the Saturday call and another case that you subsequently flagged for me on Slack. The right solution is to search for these cases on the production deployment and find their stable, production UUIDs. It would be convenient if the UUIDs were the same in order to make that "search" trivial, but maybe not worth the hassle.

**Comment by Mr0grog** [comment]
Since we’ve been talking about other development sanity/convenience issues (and about testing diffs), I threw together a stupidly simple rake task to copy pages (and their versions) from another database (so you get the right UUIDs).

I should probably push that later so it’s easy to copy data for testing, but maybe this is also how we should populate staging (instead of having the importer send to it)? Also, maybe [the seed script for local databases should use it](https://github.com/edgi-govdata-archiving/web-monitoring-db/blob/master/db/seeds.rb#L13-L21) instead a normal import? (That’s harder because of passwords, though.)

**Comment by danielballan** [comment]
> maybe this is also how we should populate staging

:+1:

> Also, maybe the seed script for local databases should use it instead a normal import? (That’s harder because of passwords, though.)

This might be worth revisiting once we have granular authorization in place. We could create a public "deploy key" that is allowed to do this one operation. If somebody starts abusing it to hammer the API, we can always revoke and revisit the strategy.

**Comment by Mr0grog** [comment]
See #183.

**Comment by Mr0grog** [comment]
I think this issue still matters, but since we’ve turned off live importing to staging, I think the relevant thing here is more like: “throw out all the data on staging and re-import a random sample of pages from production.”
