### ISSUE TITLE
Google Sheets API throttling

### ISSUE THREAD

**Issue by dphiffer** [edgi-govdata-archiving/web-monitoring-db#196]
Wonder if there should be some kind of timer in the code so that it waits before hitting the Google Sheets API too many times per minute?

I'm seeing this error when I try to load assigned pages in the UI:
```
Error retrieving data from Google Sheets: Insufficient tokens for quota 'ReadGroup' and limit 'USER-100s' of service 'sheets.googleapis.com' for consumer 'project_number:19423855495'.
```

It's also possible I did something to the UI that has made it go crazy for XHR requests, triggering the rate limit to kick in.

See also: https://github.com/edgi-govdata-archiving/web-monitoring-ui/issues/50

**Comment by Mr0grog** [comment]
Hmmmm, that seems odd. The service account I made for this is not associated with anything paid and it has unlimited requests (or 500 requets per 100 second window):

<img width="429" alt="screen shot 2018-01-10 at 11 35 39 pm" src="https://user-images.githubusercontent.com/74178/34813531-2a583310-f65f-11e7-8116-8213eb3dcfbf.png">

How did you create the service account? I did it through the cloud console (rather than the developer console); I wonder if that makes a difference…

**Comment by Mr0grog** [comment]
Oh, hahaha, just realized this is on the DB project; didn’t see that before. DB doesn’t touch Google Sheets at all; all the sheets logic is fully contained in UI. All the sheets stuff is contained in the [`server/sheet-data.js`](https://github.com/edgi-govdata-archiving/web-monitoring-ui/blob/master/server/sheet-data.js) module over there.

The reason all that lives in UI is that DB wasn’t built to be UI’s backend. DB was actually built to be an [eventually] public API service for the world to get data about changes to government web pages and to collaboratively contribute to or mine for analyzed data. So you might build tools that have nothing to do with our analysis workflow based on it. Since things like tasking are particular to what the UI is doing and not to the sort of data the DB project is focused on, it’s not included in DB.

That might be a bit esoteric and maybe that level of separation was a bad idea… certainly happy to have discussion on it if you have strong thoughts.

**Comment by Mr0grog** [comment]
I’m going to close this here; but feel free to re-post in UI if you’re still hitting it as an issue, @dphiffer.
