### ISSUE TITLE
Update bad hashes (from hashing UTF-8 encoded version of non-UTF content)

### ISSUE THREAD

**Issue by weatherpattern** [edgi-govdata-archiving/web-monitoring-db#205]
Kendra found a url with this error:
Error: Fetched content does not match hash.

https://monitoring.envirodatagov.org/page/d6c252bb-b378-4c33-babb-bf117a76facd/7de87e40-acd2-444d-9821-24076ffbfb9a..a6e5811f-cc37-4182-85aa-4cd9cbef858a

Also Jake found a similar error:
https://monitoring.envirodatagov.org/page/e679e7f4-4d78-4425-b6bc-23d26f987781/..8a270535-9871-47b8-9f2a-e2f5d6853873

FWIW, Versionista is able to render this diff.

**Comment by danielballan** [comment]
I have always thought of this pattern as a check against disk corruption, primarily. Any ideas what could be causing it? The solution might be to re-ingest the bad data. It's possible to systematically check every Version for this issue.

**Comment by Mr0grog** [comment]
In the one that works, the raw bytes hash the same as a UTF-8 encoded string.

I’m guessing that, because the one that’s a problem was from *long* ago, the issue probably has something to do with the fact that we used to get actual files from Versionista in a zip archive, so the actual bytes were provided that way and weren’t UTF-8, but we somehow hashed them as UTF-8. If that’s the issue, we shouldn’t see it in anything from the last half year because Versionista broke that export method and we have to process each string and write that out as actual UTF-8 bytes.

**Comment by danielballan** [comment]
If that's the case, the correct solution is probably to update the hashes.

**Comment by Mr0grog** [comment]
Yes, the right process is probably to go through every version and:

- If hash of bytes does not match version hash, hash a unicode-encoded version
- If hash of unicode version matches, re-import with `update=merge` to reset the hash to the bytes hash
- If hash of unicode version does not match, flag it as another issue that needs manual fixing.

**Comment by weatherpattern** [comment]
For future occurrences of this error. Is it worthwhile to still show the diff but throw a warning to the user, saying something to the effect that we can't guarantee that the version hasn't been altered? (And also logging the warning as well.) Or is that too dangerous?

**Comment by danielballan** [comment]
My experience is that users never read warnings: you have to make them full
errors if you ever want to hear about them. On the other hand, we could
ensure that instances of this problem generate a log entry and Sentry
notification to the devs and follow up that way, allowing the users to
carry on in the event that this is a false alarm, as it seems to be in this
case. I think I prefer to keep the error, but my instincts aren’t tuned for
web apps.

**Comment by Mr0grog** [comment]
I’m with @danielballan in that we should not go on and actually generate a diff in this case. We can definitely give the user a more understandable, non-technical error message.

I also think it’s a **great** idea to log these to Sentry. To that end, we should probably be raising an actual exception and letting Tornado handle it properly instead of [manually calling `send_error`](https://github.com/edgi-govdata-archiving/web-monitoring-processing/blob/master/web_monitoring/diffing_server.py#L74-L76). Sentry should probably be integrated into Tornado’s error handling (who knows, it may even have built in support like it does for Rack).

Alternatively, we could have this error tracked into Sentry from DB instead. Currently we handle the error to provide nice error responses (as a side-effect, Sentry doesn’t wind up seeing it), but  that handler could also signal Sentry.

I **do** get an e-mail for every diff that takes too long to render (it’s mostly PDFs, and at a rate of about 20-30 a day, so I really want to fix edgi-govdata-archiving/web-monitoring-processing#147 and edgi-govdata-archiving/web-monitoring-ui#179), but that’s a kind of special class of failure.

**Comment by weatherpattern** [comment]
All sounds good.
We agree that:
- We won't diff the url.
- We will continue to throw and error message (not a warning) but change the message to something a non-technical user will understand.
- We will log these to Sentry in Tornado or from DB.

**Comment by Mr0grog** [comment]
Tagging this with v0.0.2 since it seems like it’s probably a showstopper if analysts can’t fall back to Versionista when they encounter it.

**Comment by Mr0grog** [comment]
Can probably take care of edgi-govdata-archiving/web-monitoring#95 pretty efficiently.

**Comment by Mr0grog** [comment]
This is done. Source of my quick-n-dirty script is here for reference: https://gist.github.com/Mr0grog/2499576e144ec7e0e9256737d2f65a6e

**Comment by lightandluck** [comment]
🎉
