### ISSUE TITLE
WM Workflow: useful for Readme?

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/web-monitoring-db#435]
I made a table from [Rob's comment](https://github.com/qri-io/walk/issues/16#issuecomment-437785099) on Walk design re how data arrives in Scanner. Helped me understand the process, thought I'd surface here in case it was useful to others.

| What happens | What does this | How | Criteria |
|-------------|-|-------|---------|
| Versionista is scraped | [web-monitoring-versionista-scraper](https://github.com/edgi-govdata-archiving/web-monitoring-versionista-scraper) | Data is scraped from Versionista, uploaded to S3, formatted, and [POST](https://api.monitoring.envirodatagov.org/#/imports/post_imports_)ed to [-db](https://github.com/edgi-govdata-archiving/web-monitoring-db) | Runs on a cron job, formats per [GH issue comment](https://github.com/qri-io/walk/issues/16#issuecomment-437785099) |
| IA's Wayback Machine is queried for imports | [web-monitoring-processing](https://github.com/edgi-govdata-archiving/web-monitoring-processing) - this [PR](https://github.com/edgi-govdata-archiving/web-monitoring-processing/pull/174) | Data is pulled from the IA API, formatted, and [POST](https://api.monitoring.envirodatagov.org/#/imports/post_imports_)ed to [-db](https://github.com/edgi-govdata-archiving/web-monitoring-db) | Runs on a cron job, formats per [GH issue comment](https://github.com/qri-io/walk/issues/16#issuecomment-437785099) |
| New metadata arrives at [-db](https://github.com/edgi-govdata-archiving/web-monitoring-db) | Scripts running on cron jobs that do ETL via scrapes or APIs (These scripts: [Versionista scraper](https://github.com/edgi-govdata-archiving/web-monitoring-versionista-scraper), [Wayback Machine importer](https://github.com/edgi-govdata-archiving/web-monitoring-processing))| [POST](https://api.monitoring.envirodatagov.org/#/imports/post_imports_) to [/api/v0/imports](https://api.monitoring.envirodatagov.org/#/imports/post_imports_) | Contains:<ul><li> a URL for where to retrieve the raw response body of the version</li><li> a SHA-256 hash of that data</li></ul> |
| Determination is made whether or not to download the data | [-db](https://github.com/edgi-govdata-archiving/web-monitoring-db) (specifics useful?) | If the URL is in an acceptable, publicly readable location |  Acceptable location checked [per .env](https://github.com/edgi-govdata-archiving/web-monitoring-db/blob/30d976676935f5f621e18285016a137c8b55a0d8/.env.example#L26-L27) |
| URL for raw data is stored  | [-db](https://github.com/edgi-govdata-archiving/web-monitoring-db) (specifics useful?) | [-db](https://github.com/edgi-govdata-archiving/web-monitoring-db) stores URL (where? Presumably some file in our S3 bucket?) | Happens if [-db](https://github.com/edgi-govdata-archiving/web-monitoring-db) has determined not to download the data |
| Raw data is verified and stored on URL we store and maintain | [-db](https://github.com/edgi-govdata-archiving/web-monitoring-db) (specifics useful?) | Raw response data downloaded from the URL, verified against SHA-256 hash of the data from initial POST, and stores it (in production) in a public S3 bucket | Happens if [-db](https://github.com/edgi-govdata-archiving/web-monitoring-db) has determined to download the data |
| Data is accepted | Imports endpoint (at [/api/v0/imports](https://api.monitoring.envirodatagov.org/#/imports/post_imports_))| JSON array or newline-delimited JSON stream (stream preferred) | Example data in [GH issue comment](https://github.com/qri-io/walk/issues/16#issuecomment-437785099) |

Would it be useful to have this here in the readme? I think (if it's both accurate and fairly complete) it might be helpful for anyone trying to get up to speed on how this works.

But if not complete and/or if it changes frequently, prb better not to.

**Comment by Mr0grog** [comment]
This is useful! But it probably belongs here: https://github.com/edgi-govdata-archiving/web-monitoring (in the umbrella project, not in -db).

**Comment by Mr0grog** [comment]
In “URL for raw data is stored…”

> [-db](https://github.com/edgi-govdata-archiving/web-monitoring-db) stores URL (where? Presumably some file in our S3 bucket?)

Every *version* that -db stores in its database has a URL for the raw data (see the `Version.uri` field in the [“Models” section of the API docs](https://api.monitoring.envirodatagov.org/#model-Version)). The question is whether the URL is pointing at a storage location managed by -db (in practice this is always an S3 bucket, but there are pluggable storage layers) or by an outside entity.

When we’re checking whether a URL is acceptable, what we’re really doing is checking whether it’s OK to just put that URL in the version record or whether we need to download the content at the URL, put it in the storage location -db manages, and put *that new URL for the -db-managed location* in the record.

**Comment by Frijol** [comment]
What do you think, is this more or less clear than the table without the diagram?

| Diagram key | What happens | What does this | How | Criteria |
|-|-------------|-|-------|---------|
| A | Versionista is scraped | [web-monitoring-versionista-scraper](https://github.com/edgi-govdata-archiving/web-monitoring-versionista-scraper) | Data is scraped from Versionista, uploaded to S3, formatted, and [POST](https://api.monitoring.envirodatagov.org/#/imports/post_imports_)ed to [-db](https://github.com/edgi-govdata-archiving/web-monitoring-db) | Runs on a cron job, formats per [GH issue comment](https://github.com/qri-io/walk/issues/16#issuecomment-437785099) |
|B| IA's Wayback Machine is queried for imports | [web-monitoring-processing](https://github.com/edgi-govdata-archiving/web-monitoring-processing) - this [PR](https://github.com/edgi-govdata-archiving/web-monitoring-processing/pull/174) | Data is pulled from the IA API, formatted, and [POST](https://api.monitoring.envirodatagov.org/#/imports/post_imports_)ed to [-db](https://github.com/edgi-govdata-archiving/web-monitoring-db) | Runs on a cron job, formats per [GH issue comment](https://github.com/qri-io/walk/issues/16#issuecomment-437785099) |
|C| New metadata arrives at [-db](https://github.com/edgi-govdata-archiving/web-monitoring-db) | Scripts running on cron jobs that do ETL via scrapes or APIs (These scripts: [Versionista scraper](https://github.com/edgi-govdata-archiving/web-monitoring-versionista-scraper), [Wayback Machine importer](https://github.com/edgi-govdata-archiving/web-monitoring-processing))| [POST](https://api.monitoring.envirodatagov.org/#/imports/post_imports_) to [/api/v0/imports](https://api.monitoring.envirodatagov.org/#/imports/post_imports_) | Contains:<ul><li> a URL for where to retrieve the raw response body of the version</li><li> a SHA-256 hash of that data</li></ul> |
|D| Determination is made whether or not to download the data | [-db](https://github.com/edgi-govdata-archiving/web-monitoring-db) (specifics useful?) | If the URL is in an acceptable, publicly readable location |  Acceptable location checked [per .env](https://github.com/edgi-govdata-archiving/web-monitoring-db/blob/30d976676935f5f621e18285016a137c8b55a0d8/.env.example#L26-L27) |
|E1| URL for raw data is stored  | [-db](https://github.com/edgi-govdata-archiving/web-monitoring-db) (specifics useful?) | [-db](https://github.com/edgi-govdata-archiving/web-monitoring-db) stores URL (where? Presumably some file in our S3 bucket?) | Happens if [-db](https://github.com/edgi-govdata-archiving/web-monitoring-db) has determined not to download the data |
|E2| Raw data is verified and stored on URL we store and maintain | [-db](https://github.com/edgi-govdata-archiving/web-monitoring-db) (specifics useful?) | Raw response data downloaded from the URL, verified against SHA-256 hash of the data from initial POST, and stores it (in production) in a public S3 bucket | Happens if [-db](https://github.com/edgi-govdata-archiving/web-monitoring-db) has determined to download the data |
|F| Data is accepted | Imports endpoint (at [/api/v0/imports](https://api.monitoring.envirodatagov.org/#/imports/post_imports_))| JSON array or newline-delimited JSON stream (stream preferred) | Example data in [GH issue comment](https://github.com/qri-io/walk/issues/16#issuecomment-437785099) |

Diagram of flow:

```mermaid
graph TD;
    A-->B;
    B-->C;
    C-->D;
    D-->E1;
    D-->E2;
    E1-->F;
    E2-->F;
```

![diagram render](https://user-images.githubusercontent.com/454690/49037221-8089a100-f16e-11e8-90c0-445659fca36a.png)

**Comment by Mr0grog** [comment]
A little unicode might help in the table, too:

| Diagram key | What happens | What does this | How | Criteria |
|-|-------------|-|-------|---------|
|D| Determination is made whether or not to download the data | [-db](https://github.com/edgi-govdata-archiving/web-monitoring-db) (specifics useful?) | If the URL is in an acceptable, publicly readable location |  Acceptable location checked [per .env](https://github.com/edgi-govdata-archiving/web-monitoring-db/blob/30d976676935f5f621e18285016a137c8b55a0d8/.env.example#L26-L27) |
|    ↳ E1| URL for raw data is stored  | [-db](https://github.com/edgi-govdata-archiving/web-monitoring-db) (specifics useful?) | [-db](https://github.com/edgi-govdata-archiving/web-monitoring-db) stores URL (where? Presumably some file in our S3 bucket?) | Happens if [-db](https://github.com/edgi-govdata-archiving/web-monitoring-db) has determined not to download the data |
|    ↳ E2| Raw data is verified and stored on URL we store and maintain | [-db](https://github.com/edgi-govdata-archiving/web-monitoring-db) (specifics useful?) | Raw response data downloaded from the URL, verified against SHA-256 hash of the data from initial POST, and stores it (in production) in a public S3 bucket | Happens if [-db](https://github.com/edgi-govdata-archiving/web-monitoring-db) has determined to download the data |
|F| Data is accepted | Imports endpoint (at [/api/v0/imports](https://api.monitoring.envirodatagov.org/#/imports/post_imports_))| JSON array or newline-delimited JSON stream (stream preferred) | Example data in [GH issue comment](https://github.com/qri-io/walk/issues/16#issuecomment-437785099) |

Also (F) quite makes sense as-is. The what/how/criteria columns are really more a part of (C). When you POST to `/api/v0/imports`, we just save the post body, queue a job to process it, and return a response with the job ID so you can check on the status. Then sometime later, a different process picks the job up off the queue, loads the ND-JSON stream (or JSON array) you posted, parses it, and for each object listed, it does (D → E1/2).

So there’s “accepting data from outside” which happens immediately, and then “creating actual records in our database (and downloading data if necessary)” which happens later, separately.

**Comment by Mr0grog** [comment]
This was done in edgi-govdata-archiving/web-monitoring#124. We should’ve closed this a while ago!
