### ISSUE TITLE
Should creating a new Page require a separate request?

### ISSUE THREAD

**Issue by danielballan** [edgi-govdata-archiving/web-monitoring-db#57]
If I understand correctly, the current import mechanism matches new Versions to their Pages using `page_url`. When it receives a `page_url` it doesn't recognize, it creates a new Page. Page attributes (like title, site, agency) are provided inline with the Version attributes. I can imagine some sources of ambiguity:

* a known `page_url` but a new `page_title`
* a new `page_url` that we actually want to keep as part of the same logical `Page` (a case that we don't quite support yet but want to support in the future)

I think I would prefer if the app required any new Page to be created explicitly in a separate request, returning a page_uuid that must then be included in requests to import Versions for that Page. This change would push the work of resolving ambiguities onto the caller requesting an import. Also, since a new Page needs special primer-related metadata that is not as automated as Version ingest, separating page creation from bulk Version importing seems logical.

This alternative did not occur me when reviewing #32 and I don't think it has been discussed anywhere.

**Comment by Mr0grog** [comment]
I definitely hear the concern about supporting a future where we can model that fact that a page *moved* URLs, but am concerned about how much extra work that pushes onto an importer. Not only would the process of importing become complex and multi-stepped, but an importer would have to maintain a persistent data store and have some sort of initial setup process, since no aspect of an external source will be able to canonically identify a page.

I am especially wary of taking on this work in the near term because we are still 100% failing to provide an end product of any utility at all to our actual analysts, which is the primary point of this whole endeavor. We are an analysis tool first and an archive second. I am not excited about spending time and effort on a thing that also makes the entire rest of the infrastructure require more time and effort until we are well past v0 for a working analyst UI (unless there’s a serious immediate problem—and I would argue there is not).

*I guess what I’m saying is: I see the value of this, but we are a long way from realizing any of the functionality that would make it useful and making the change now imposes a lot of work that is in the way of other, more important work in the near term.*

> Since a new Page needs special primer-related metadata that is not as automated as Version ingest, separating page creation from bulk Version importing seems logical.

I actually think it’s beneficial that the records we import represent a complete, standalone picture of a page at a point in time. It means imports can act as canonical records, while I tend to think of the separation and relations we have in the DB as an implementation detail to make the data more convenient to query and analyze.

> a known `page_url` but a new `page_title`

I think this is a totally separate issue. Versionista handles this by updating the Page’s title to match that of the latest version, which we could very easily do. A related question is: should actually be storing the `page_title` on Version records, leaving the column on the Page record as a temporary, non-canonical view on that (like a Change record’s `current_annotation` is for its list of child Annotations).

**Comment by danielballan** [comment]
> I actually think it’s beneficial that the records we import represent a complete, standalone picture of a page at a point in time.

Good point, that does sound useful. I would still argue that the semantics that we impose (site, agency) should be separate and de-referenced with a uuid to avoid ambiguous conflicts.

> A related question is: should actually be storing the page_title on Version records, leaving the column on the Page record as a temporary, non-canonical view on that (like a Change record’s current_annotation is for its list of child Annotations).

I would argue yes. (When we originally planned the schema, I thought 'title' was some primer jargon; I didn't realize it was literally the title tag.)

**Comment by danielballan** [comment]
Forgot to respond about moved URLs: fully agree, totally comfortable with punting on that. We can ignore moved URL problems until we decide to track them. Separately, the 'page title' issue seems more urgent because I do expect some "conflicting" page titles when we start bulk-importing the PF data dump.

**Comment by Mr0grog** [comment]
> I would still argue that the semantics that we impose (site, agency) should be separate and de-referenced with a uuid to avoid ambiguous conflicts.

FWIW, these are not part of the matching algorithm (except for Versionista imports, which are unfortunately special at the moment). I think this will necessarily have to change/get fixed with #24, too.
