### ISSUE TITLE
Relative links in AWS snapshots are broken

### ISSUE THREAD

**Issue by lightandluck** [edgi-govdata-archiving/web-monitoring-db#91]
Relative links (e.g. `<a href="/blog/8-powerful-facts-about-interiors-role-american-energy-dominance">8 Powerful Facts About Interior's Role in American Energy Dominance</a>`) in the AWS snapshots are broken because they try to use AWS as the base domain, so point to urls that don't exist.

### Steps to reproduce
1. Go to [example](https://edgi-versionista-archive.s3.amazonaws.com/versionista2/74535-6250656/version-11951026.html)
2. Any link that's relative goes to error page

### Context
If analysts or diffing services use this html, they will not be able to navigate and explore links which is common practice in both stages of analysis.

### Proposed Solution
Add a `<base>` tag to the `head` of documents with the original domain of the snapshot.
For example we can go into the dev console of the above page, add `<base href="https://www.doi.gov">`, and links will work again.

**Comment by lightandluck** [comment]
Probably too much trouble to fix existing snapshots, but I think it's important to fix this going forward.

**Comment by Mr0grog** [comment]
I’m not sure we should be changing this at all. We’ve actually *gone out of our way* to make sure that the archived content is this way and not using normalized URLs as it originally was way back when I was first scraping from Versionista. That’s so that we have a real archive of the raw content as close as possible to what the web server responded with and so that our diffs can be accurate.

That said, we could provide an endpoint that returns the raw content with the `base` element added (it would be harder for DB to do this for diffs because we don’t know whether a diff is returning HTML). The UI app could also do this itself.

**Comment by Mr0grog** [comment]
Similarly, another thing we should address here is inserting some JS at the top of the page to neutralize any iframe escape scripts a page might use.

For example, this page: https://www.nrcs.usda.gov/wps/portal/nrcs/main/national/landuse/forestry/sustain uses the following escape script:

```html
<script type="text/javascript">
  if (self === top) {
    var antiClickjack = document.getElementById("antiClickjack");
    antiClickjack.parentNode.removeChild(antiClickjack);
  } else {
    top.location = self.location;
  }
</script>
```

**Comment by Mr0grog** [comment]
Side note: the above issue (iframe escapes) got fixed in edgi-govdata-archiving/web-monitoring-ui#82 by sandboxing the iframes, so probably not worth worrying about here.

**Comment by Mr0grog** [comment]
On this and the related issue of rendering an old page’s sub-resources correctly (it was on my mind today for some reason)…

I toyed with the idea of using a service worker in the client to modify subresource URLs to point to `http://web.archive.org/web/{capture_time}id_/{url of resource}`, but to do that, we’d have to have an actual page that we are loading into the iframe in the client (right now we populate with HTML source code, which leaves the iframe with a null origin, which disables service workers).

So for service workers, we’d have to either:

- add a proxy on the client server to get version source from S3 or the API (in order to give the frame an origin) or
- implement a special endpoint here in the DB API that returns view-friendly modified source code for a version (this is also how we’d do the less-fancy approach of just modifying all the `src` and `href` attributes in the HTML source code)

(Service worker pros: happily handles all requests, not just attributes we can identify in the HTML elements of the source code; cons: doesn’t work in all browsers)

**Comment by Mr0grog** [comment]
I think there are still problems to solve with subresources (images, scripts, css), but we *did* [add a `<base>` element in on the UI side](https://github.com/edgi-govdata-archiving/web-monitoring-ui/blob/084ebb2cf288f1a739f6b29b1a97b411f2e4036d/src/components/sandboxed-html.jsx#L39-L48) that fixed links a while back. I think that was the part of this that was really critical, so I’m moving this out of the v0.0.2 milestone.
